version: '2'
services:
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
    networks:
      static-network:
        ipv4_address: 172.40.0.12
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony
    volumes:
      - mysql-data:/var/lib/mysql:rw
    networks:
      static-network:
        ipv4_address: 172.40.0.11
  php:
    build:
      context: ./docker/dockerfiles/php/
        args:
          - user=${USER}
        ports:
          - "8080:80" #nginx
        volumes:
          - ./app/example.mysite.api:/usr/share/nginx/html:rw
          - ./sites/:/etc/nginx/sites-enabled/
        links:
          - mysql
          - maildev
        networks:
          static-network:
            ipv4_address: 172.40.0.10
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.40.0.0/24
volumes:
  mysql-data: